version: "3.9"

services:
  api:
    image: rngapi
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/health"]
      interval: 30s
      retries: 3
      timeout: 10s
    networks:
      - app-network
    ports:
      - "8090:8090"

  web:
    # Собираем из Dockerfile фронта
    build:
      context: ./rngfrontend
      dockerfile: ./Dockerfile
    image: rngweb
    restart: always
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      retries: 3
      timeout: 5s
    networks:
      - app-network
    ports:
      - "8080:80"

networks:
  app-network:
    driver: bridge
