version: "3.8"

services:
  api:
    build:
      context: ./rngbackend
      dockerfile: ./services/api/Dockerfile
    image: rngapi
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/health"]
      interval: 30s
      retries: 3
      timeout: 10s
    ports:
      - "8090:8090"
    networks: [app-network]

  web:
    build:
      context: ./rngfrontend
      dockerfile: ./Dockerfile
    image: rngweb
    restart: always
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      retries: 3
      timeout: 5s
    ports:
      - "8080:80"
    networks: [app-network]

networks:
  app-network:
    driver: bridge
